In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("bank.csv")

In [3]:
dataset.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [4]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
dataset["marital"].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [6]:
dataset["job"].unique()

array(['admin.', 'technician', 'services', 'management', 'retired',
       'blue-collar', 'unemployed', 'entrepreneur', 'housemaid',
       'unknown', 'self-employed', 'student'], dtype=object)

In [7]:
dataset["education"].unique()

array(['secondary', 'tertiary', 'primary', 'unknown'], dtype=object)

In [8]:
dataset["contact"].unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)

In [9]:
dataset["month"].unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

In [10]:
dataset["poutcome"].unique()

array(['unknown', 'other', 'failure', 'success'], dtype=object)

In [11]:
def t_marital(a):
    if a=="married":
        return 0
    if a=="single":
        return 1
    if a=="divorced":
        return 2

In [12]:
dataset["marital"]=dataset["marital"].apply(t_marital)
dataset

age          job  marital  education default  balance housing loan  \
0       59       admin.        0  secondary      no     2343     yes   no   
1       56       admin.        0  secondary      no       45      no   no   
2       41   technician        0  secondary      no     1270     yes   no   
3       55     services        0  secondary      no     2476     yes   no   
4       54       admin.        0   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar        1    primary      no        1     yes   no   
11158   39     services        0  secondary      no      733      no   no   
11159   32   technician        1  secondary      no       29      no   no   
11160   43   technician        0  secondary      no        0      no  yes   
11161   34   technician        0  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [13]:
def t_job(a):
    if a=="admin.":
        return 0
    if a=="technician":
        return 1
    if a=="services":
        return 2
    if a=="management":
        return 3
    if a=="retired":
        return 4
    if a=="blue-collar":
        return 5
    if a=="unemployed":
        return 6
    if a=="entrepreneur":
        return 7
    if a=="housemaid":
        return 8
    if a=="unknown":
        return 9
    if a=="self-employed":
        return 10
    if a=="student":
        return 11

In [14]:
dataset["job"]=dataset["job"].apply(t_job)
dataset

age  job  marital  education default  balance housing loan   contact  \
0       59    0        0  secondary      no     2343     yes   no   unknown   
1       56    0        0  secondary      no       45      no   no   unknown   
2       41    1        0  secondary      no     1270     yes   no   unknown   
3       55    2        0  secondary      no     2476     yes   no   unknown   
4       54    0        0   tertiary      no      184      no   no   unknown   
...    ...  ...      ...        ...     ...      ...     ...  ...       ...   
11157   33    5        1    primary      no        1     yes   no  cellular   
11158   39    2        0  secondary      no      733      no   no   unknown   
11159   32    1        1  secondary      no       29      no   no  cellular   
11160   43    1        0  secondary      no        0      no  yes  cellular   
11161   34    1        0  secondary      no        0      no   no  cellular   

       day month  duration  campaign  pdays  previous poutcome deposit  
0        5   may      1042         1     -1         0  unknown     yes  
1        5   may      1467         1     -1         0  unknown     yes  
2        5   may      1389         1     -1         0  unknown     yes  
3        5   may       579         1     -1         0  unknown     yes  
4        5   may       673         2     -1         0  unknown     yes  
...    ...   ...       ...       ...    ...       ...      ...     ...  
11157   20   apr       257         1     -1         0  unknown      no  
11158   16   jun        83         4     -1         0  unknown      no  
11159   19   aug       156         2     -1         0  unknown      no  
11160    8   may         9         2    172         5  failure      no  
11161    9   jul       628         1     -1         0  unknown      no  

[11162 rows x 17 columns]

In [15]:
def t_edu(a):
    if a=="secondary":
        return 0
    if a=="tertiary":
        return 1
    if a=="primary":
        return 2
    if a=="unknown":
        return 3

In [16]:
dataset["education"]=dataset["education"].apply(t_edu)
dataset

age  job  marital  education default  balance housing loan   contact  \
0       59    0        0          0      no     2343     yes   no   unknown   
1       56    0        0          0      no       45      no   no   unknown   
2       41    1        0          0      no     1270     yes   no   unknown   
3       55    2        0          0      no     2476     yes   no   unknown   
4       54    0        0          1      no      184      no   no   unknown   
...    ...  ...      ...        ...     ...      ...     ...  ...       ...   
11157   33    5        1          2      no        1     yes   no  cellular   
11158   39    2        0          0      no      733      no   no   unknown   
11159   32    1        1          0      no       29      no   no  cellular   
11160   43    1        0          0      no        0      no  yes  cellular   
11161   34    1        0          0      no        0      no   no  cellular   

       day month  duration  campaign  pdays  previous poutcome deposit  
0        5   may      1042         1     -1         0  unknown     yes  
1        5   may      1467         1     -1         0  unknown     yes  
2        5   may      1389         1     -1         0  unknown     yes  
3        5   may       579         1     -1         0  unknown     yes  
4        5   may       673         2     -1         0  unknown     yes  
...    ...   ...       ...       ...    ...       ...      ...     ...  
11157   20   apr       257         1     -1         0  unknown      no  
11158   16   jun        83         4     -1         0  unknown      no  
11159   19   aug       156         2     -1         0  unknown      no  
11160    8   may         9         2    172         5  failure      no  
11161    9   jul       628         1     -1         0  unknown      no  

[11162 rows x 17 columns]

In [17]:
def t_con(a):
    if a=="unknown":
        return 0
    if a=="cellular":
        return 1
    if a=="telephone":
        return 2

In [18]:
dataset["contact"]=dataset["contact"].apply(t_con)
dataset

age  job  marital  education default  balance housing loan  contact  \
0       59    0        0          0      no     2343     yes   no        0   
1       56    0        0          0      no       45      no   no        0   
2       41    1        0          0      no     1270     yes   no        0   
3       55    2        0          0      no     2476     yes   no        0   
4       54    0        0          1      no      184      no   no        0   
...    ...  ...      ...        ...     ...      ...     ...  ...      ...   
11157   33    5        1          2      no        1     yes   no        1   
11158   39    2        0          0      no      733      no   no        0   
11159   32    1        1          0      no       29      no   no        1   
11160   43    1        0          0      no        0      no  yes        1   
11161   34    1        0          0      no        0      no   no        1   

       day month  duration  campaign  pdays  previous poutcome deposit  
0        5   may      1042         1     -1         0  unknown     yes  
1        5   may      1467         1     -1         0  unknown     yes  
2        5   may      1389         1     -1         0  unknown     yes  
3        5   may       579         1     -1         0  unknown     yes  
4        5   may       673         2     -1         0  unknown     yes  
...    ...   ...       ...       ...    ...       ...      ...     ...  
11157   20   apr       257         1     -1         0  unknown      no  
11158   16   jun        83         4     -1         0  unknown      no  
11159   19   aug       156         2     -1         0  unknown      no  
11160    8   may         9         2    172         5  failure      no  
11161    9   jul       628         1     -1         0  unknown      no  

[11162 rows x 17 columns]

In [19]:
def t_mon(a):
    if a=="jan":
        return 0
    if a=="feb":
        return 1
    if a=="mar":
        return 2
    if a=="apr":
        return 3
    if a=="may":
        return 4
    if a=="jun":
        return 5
    if a=="jul":
        return 6
    if a=="aug":
        return 7
    if a=="sep":
        return 8
    if a=="oct":
        return 9
    if a=="nov":
        return 10
    if a=="dec":
        return 11

In [20]:
dataset["month"]=dataset["month"].apply(t_mon)
dataset

age  job  marital  education default  balance housing loan  contact  \
0       59    0        0          0      no     2343     yes   no        0   
1       56    0        0          0      no       45      no   no        0   
2       41    1        0          0      no     1270     yes   no        0   
3       55    2        0          0      no     2476     yes   no        0   
4       54    0        0          1      no      184      no   no        0   
...    ...  ...      ...        ...     ...      ...     ...  ...      ...   
11157   33    5        1          2      no        1     yes   no        1   
11158   39    2        0          0      no      733      no   no        0   
11159   32    1        1          0      no       29      no   no        1   
11160   43    1        0          0      no        0      no  yes        1   
11161   34    1        0          0      no        0      no   no        1   

       day  month  duration  campaign  pdays  previous poutcome deposit  
0        5      4      1042         1     -1         0  unknown     yes  
1        5      4      1467         1     -1         0  unknown     yes  
2        5      4      1389         1     -1         0  unknown     yes  
3        5      4       579         1     -1         0  unknown     yes  
4        5      4       673         2     -1         0  unknown     yes  
...    ...    ...       ...       ...    ...       ...      ...     ...  
11157   20      3       257         1     -1         0  unknown      no  
11158   16      5        83         4     -1         0  unknown      no  
11159   19      7       156         2     -1         0  unknown      no  
11160    8      4         9         2    172         5  failure      no  
11161    9      6       628         1     -1         0  unknown      no  

[11162 rows x 17 columns]

In [21]:
def t_out(a):
    if a=="unknown":
        return 0
    if a=="other":
        return 1
    if a=="failure":
        return 2
    if a=="success":
        return 3

In [22]:
dataset["poutcome"]=dataset["poutcome"].apply(t_out)
dataset

age  job  marital  education default  balance housing loan  contact  \
0       59    0        0          0      no     2343     yes   no        0   
1       56    0        0          0      no       45      no   no        0   
2       41    1        0          0      no     1270     yes   no        0   
3       55    2        0          0      no     2476     yes   no        0   
4       54    0        0          1      no      184      no   no        0   
...    ...  ...      ...        ...     ...      ...     ...  ...      ...   
11157   33    5        1          2      no        1     yes   no        1   
11158   39    2        0          0      no      733      no   no        0   
11159   32    1        1          0      no       29      no   no        1   
11160   43    1        0          0      no        0      no  yes        1   
11161   34    1        0          0      no        0      no   no        1   

       day  month  duration  campaign  pdays  previous  poutcome deposit  
0        5      4      1042         1     -1         0         0     yes  
1        5      4      1467         1     -1         0         0     yes  
2        5      4      1389         1     -1         0         0     yes  
3        5      4       579         1     -1         0         0     yes  
4        5      4       673         2     -1         0         0     yes  
...    ...    ...       ...       ...    ...       ...       ...     ...  
11157   20      3       257         1     -1         0         0      no  
11158   16      5        83         4     -1         0         0      no  
11159   19      7       156         2     -1         0         0      no  
11160    8      4         9         2    172         5         2      no  
11161    9      6       628         1     -1         0         0      no  

[11162 rows x 17 columns]

In [23]:
dataset.head()

age  job  marital  education default  balance housing loan  contact  day  \
0   59    0        0          0      no     2343     yes   no        0    5   
1   56    0        0          0      no       45      no   no        0    5   
2   41    1        0          0      no     1270     yes   no        0    5   
3   55    2        0          0      no     2476     yes   no        0    5   
4   54    0        0          1      no      184      no   no        0    5   

   month  duration  campaign  pdays  previous  poutcome deposit  
0      4      1042         1     -1         0         0     yes  
1      4      1467         1     -1         0         0     yes  
2      4      1389         1     -1         0         0     yes  
3      4       579         1     -1         0         0     yes  
4      4       673         2     -1         0         0     yes

In [24]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["default"]=le.fit_transform(dataset["default"])
dataset["deposit"]=le.fit_transform(dataset["deposit"])
dataset["housing"]=le.fit_transform(dataset["housing"])
dataset["loan"]=le.fit_transform(dataset["loan"])
dataset

age  job  marital  education  default  balance  housing  loan  contact  \
0       59    0        0          0        0     2343        1     0        0   
1       56    0        0          0        0       45        0     0        0   
2       41    1        0          0        0     1270        1     0        0   
3       55    2        0          0        0     2476        1     0        0   
4       54    0        0          1        0      184        0     0        0   
...    ...  ...      ...        ...      ...      ...      ...   ...      ...   
11157   33    5        1          2        0        1        1     0        1   
11158   39    2        0          0        0      733        0     0        0   
11159   32    1        1          0        0       29        0     0        1   
11160   43    1        0          0        0        0        0     1        1   
11161   34    1        0          0        0        0        0     0        1   

       day  month  duration  campaign  pdays  previous  poutcome  deposit  
0        5      4      1042         1     -1         0         0        1  
1        5      4      1467         1     -1         0         0        1  
2        5      4      1389         1     -1         0         0        1  
3        5      4       579         1     -1         0         0        1  
4        5      4       673         2     -1         0         0        1  
...    ...    ...       ...       ...    ...       ...       ...      ...  
11157   20      3       257         1     -1         0         0        0  
11158   16      5        83         4     -1         0         0        0  
11159   19      7       156         2     -1         0         0        0  
11160    8      4         9         2    172         5         2        0  
11161    9      6       628         1     -1         0         0        0  

[11162 rows x 17 columns]

In [25]:
x=dataset.iloc[:,0:16].values
y=dataset.iloc[:,16].values

In [26]:
x

array([[ 59,   0,   0, ...,  -1,   0,   0],
       [ 56,   0,   0, ...,  -1,   0,   0],
       [ 41,   1,   0, ...,  -1,   0,   0],
       ...,
       [ 32,   1,   1, ...,  -1,   0,   0],
       [ 43,   1,   0, ..., 172,   5,   2],
       [ 34,   1,   0, ...,  -1,   0,   0]], dtype=int64)

In [27]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [29]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [30]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [31]:
ypred=lr.predict(x_test)
ypred

array([1, 1, 0, ..., 1, 1, 1])

In [32]:
y_test

array([0, 1, 0, ..., 1, 1, 1])

In [33]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(ypred,y_test)
accuracy

0.8029556650246306

In [34]:
dataset.head(1)

age  job  marital  education  default  balance  housing  loan  contact  \
0   59    0        0          0        0     2343        1     0        0   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    5      4      1042         1     -1         0         0        1

In [35]:
lr.predict(sc.transform([[20,1,0,1,0,5678,1,0,3,5,7,590,0,1,1,1]]))

array([1])